### ISSUE TITLE
missing nodelet dependencies

### ISSUE THREAD

**Issue by tkruse** [ros-perception/perception_pcl#1]
building desktop-full from source, pcl_ros fails:
Adding "nodelet nodelet_topic_tools" to find_package fixes that.

Compile errors below:

In file included from /home/kruset/groovy_underlay/src/pcl_ros/src/pcl_ros/io/concatenate_fields.cpp:42:0:
/home/kruset/groovy_underlay/src/pcl_ros/include/pcl_ros/io/concatenate_fields.h:42:29: fatal error: nodelet/nodelet.h: No such file or directory

/home/kruset/groovy_underlay/src/pcl_ros/src/pcl_ros/io/io.cpp:42:45: fatal error: nodelet_topic_tools/nodelet_mux.h: No such file or directory

**Comment by vrabaud** [comment]
thx, re-releasing now.
