### ISSUE TITLE
Symbol lookup error / undefined symbol

### ISSUE THREAD

**Issue by jokla** [ros-perception/perception_pcl#125]
Hi,

I tried to launch the "[ConvexHull planar surface reconstruction](http://wiki.ros.org/pcl_ros/Tutorials/ConvexHull%20planar%20surface%20reconstruction)" example in the tutorial but I get this error:

 `/opt/ros/indigo/lib/nodelet/nodelet: symbol lookup error: /opt/ros/indigo/lib//libpcl_ros_features.so: undefined symbol: _ZN3pcl6search6KdTreeINS_8PointXYZEEC1Eb`

It is related to `pcl::search::KdTree<pcl::PointXYZ>::KdTree(bool)` , but I have the following libraries installed on my machine (via apt-get): libpcl-kdtree-1.7 libpcl-kdtree-1.7-dev libpcl-kdtree-dev.

I have installed ros-indigo-pcl-ros via apt-get. I am using Ubuntu 14.04, ROS Indigo. 

PS: if I use the package built from source I don't have this problem.

Thanks!

**Comment by SteveMacenski** [comment]
Is this still an issue?

Indigo is EOL, closing but if it propogates to Kinetic or Melodic let me know
