### ISSUE TITLE
Linking issue in bag_to_pcd

### ISSUE THREAD

**Issue by DeFrenZ** [ros-perception/perception_pcl#14]
I have an issue with linking libraries to that executable. CMake does all right in finding all libs, but then in the making process i get:

Scanning dependencies of target bag_to_pcd
[  5%] Building CXX object CMakeFiles/bag_to_pcd.dir/tools/bag_to_pcd.cpp.o
Linking CXX executable /Users/DeFrenZ/ros_catkin_ws/devel_isolated/pcl_ros/lib/pcl_ros/bag_to_pcd
Undefined symbols for architecture x86_64:
  "pcl::PCDWriter::writeASCII(std::string const&, sensor_msgs::PointCloud2_std::allocator<void > const&, Eigen::Matrix<float, 4, 1, 0, 4, 1> const&, Eigen::Quaternion<float, 0> const&, int)", referenced from:
      pcl::PCDWriter::write(std::string const&, sensor_msgs::PointCloud2_std::allocator<void > const&, Eigen::Matrix<float, 4, 1, 0, 4, 1> const&, Eigen::Quaternion<float, 0> const&, bool) in bag_to_pcd.cpp.o
  "pcl::PCDWriter::writeBinary(std::string const&, sensor_msgs::PointCloud2_std::allocator<void > const&, Eigen::Matrix<float, 4, 1, 0, 4, 1> const&, Eigen::Quaternion<float, 0> const&)", referenced from:
      pcl::PCDWriter::write(std::string const&, sensor_msgs::PointCloud2_std::allocator<void > const&, Eigen::Matrix<float, 4, 1, 0, 4, 1> const&, Eigen::Quaternion<float, 0> const&, bool) in bag_to_pcd.cpp.o
ld: symbol(s) not found for architecture x86_64

Any idea why? those functions don't even appear in bag_to_pcd.cpp, even if savePCDFile(...) does. But <pcl/io/pcd_io.h> is the file where those should be defined, and I've also checked the CMake generated files and they correctly use the path of the .dylib and .h that I need...

Mac OS X 10.8, pcl got from trunk (and already builded with catkin)

**Comment by jkammerl** [comment]
I am not sure. It could be related to a mismatch of the PointCloud2 message which is defined within ROS as well as within PCL. I saw similar linker errors that were related to this. Could you check which message headers are included on your machine?

**Comment by DeFrenZ** [comment]
I must say it does link correctly src/transform.cpp which uses PointCloud2...

pcl did generate some msgs headers, but I can't find them in depend.make (made from CMake), while there are normal ros ones with the same names (PointCloud2.h is one of them)

Basically the ignored headers seem to be:
sensor_msgs/Image.h
sensor_msgs/PointCloud2.h
sensor_msgs/PointField.h
std_msgs/Header.h

I suppose I should make see those headers and not the other ones, what would you suggest to do here?

**Comment by DeFrenZ** [comment]
I'm listing here all the linking errors for all the files that have them:
(I'm also noticing many headers refer to *Config.h files which are not in the source...)

Scanning dependencies of target convert_pcd_to_image
[100%] Building CXX object CMakeFiles/convert_pcd_to_image.dir/tools/convert_pcd_to_image.cpp.o
Linking CXX executable /Users/DeFrenZ/ros_catkin_ws/devel_isolated/pcl_ros/lib/pcl_ros/convert_pcd_to_image
Undefined symbols for architecture x86_64:
  "pcl::PCDReader::read(std::string const&, sensor_msgs::PointCloud2_std::allocator<void >&, int)", referenced from:
      pcl::io::loadPCDFile(std::string const&, sensor_msgs::PointCloud2_std::allocator<void >&) in convert_pcd_to_image.cpp.o
ld: symbol(s) not found for architecture x86_64

Scanning dependencies of target pointcloud_to_pcd
[100%] Building CXX object CMakeFiles/pointcloud_to_pcd.dir/tools/pointcloud_to_pcd.cpp.o
Linking CXX executable /Users/DeFrenZ/ros_catkin_ws/devel_isolated/pcl_ros/lib/pcl_ros/pointcloud_to_pcd
Undefined symbols for architecture x86_64:
  "pcl::PCDWriter::writeASCII(std::string const&, sensor_msgs::PointCloud2_std::allocator<void > const&, Eigen::Matrix<float, 4, 1, 0, 4, 1> const&, Eigen::Quaternion<float, 0> const&, int)", referenced from:
      pcl::PCDWriter::write(std::string const&, sensor_msgs::PointCloud2_std::allocator<void > const&, Eigen::Matrix<float, 4, 1, 0, 4, 1> const&, Eigen::Quaternion<float, 0> const&, bool) in pointcloud_to_pcd.cpp.o
  "pcl::PCDWriter::writeBinary(std::string const&, sensor_msgs::PointCloud2_std::allocator<void > const&, Eigen::Matrix<float, 4, 1, 0, 4, 1> const&, Eigen::Quaternion<float, 0> const&)", referenced from:
      pcl::PCDWriter::write(std::string const&, sensor_msgs::PointCloud2_std::allocator<void > const&, Eigen::Matrix<float, 4, 1, 0, 4, 1> const&, Eigen::Quaternion<float, 0> const&, bool) in pointcloud_to_pcd.cpp.o
ld: symbol(s) not found for architecture x86_64

Scanning dependencies of target pcd_to_pointcloud
[100%] Building CXX object CMakeFiles/pcd_to_pointcloud.dir/tools/pcd_to_pointcloud.cpp.o
Linking CXX executable /Users/DeFrenZ/ros_catkin_ws/devel_isolated/pcl_ros/lib/pcl_ros/pcd_to_pointcloud
Undefined symbols for architecture x86_64:
  "pcl::PCDReader::read(std::string const&, sensor_msgs::PointCloud2_std::allocator<void >&, int)", referenced from:
      pcl::io::loadPCDFile(std::string const&, sensor_msgs::PointCloud2_std::allocator<void >&) in pcd_to_pointcloud.cpp.o
ld: symbol(s) not found for architecture x86_64

Scanning dependencies of target pcl_ros_io
[ 33%] Building CXX object CMakeFiles/pcl_ros_io.dir/src/pcl_ros/io/io.cpp.o
[ 50%] Building CXX object CMakeFiles/pcl_ros_io.dir/src/pcl_ros/io/concatenate_fields.cpp.o
[ 66%] Building CXX object CMakeFiles/pcl_ros_io.dir/src/pcl_ros/io/concatenate_data.cpp.o
[ 83%] Building CXX object CMakeFiles/pcl_ros_io.dir/src/pcl_ros/io/pcd_io.cpp.o
[100%] Building CXX object CMakeFiles/pcl_ros_io.dir/src/pcl_ros/io/bag_io.cpp.o
Linking CXX shared library /Users/DeFrenZ/ros_catkin_ws/devel_isolated/pcl_ros/lib/libpcl_ros_io.dylib
Undefined symbols for architecture x86_64:
  "pcl::concatenatePointCloud(sensor_msgs::PointCloud2_std::allocator<void > const&, sensor_msgs::PointCloud2_std::allocator<void > const&, sensor_msgs::PointCloud2_std::allocator<void >&)", referenced from:
      pcl_ros::PointCloudConcatenateDataSynchronizer::combineClouds(sensor_msgs::PointCloud2_std::allocator<void > const&, sensor_msgs::PointCloud2_std::allocator<void > const&, sensor_msgs::PointCloud2_std::allocator<void >&) in concatenate_data.cpp.o
  "pcl::PCDReader::read(std::string const&, sensor_msgs::PointCloud2_std::allocator<void >&, int)", referenced from:
      pcl_ros::PCDReader::onInit() in pcd_io.cpp.o
  "pcl::PCDWriter::writeASCII(std::string const&, sensor_msgs::PointCloud2_std::allocator<void > const&, Eigen::Matrix<float, 4, 1, 0, 4, 1> const&, Eigen::Quaternion<float, 0> const&, int)", referenced from:
      pcl::PCDWriter::write(std::string const&, sensor_msgs::PointCloud2_std::allocator<void > const&, Eigen::Matrix<float, 4, 1, 0, 4, 1> const&, Eigen::Quaternion<float, 0> const&, bool) in pcd_io.cpp.o
  "pcl::PCDWriter::writeBinary(std::string const&, sensor_msgs::PointCloud2_std::allocator<void > const&, Eigen::Matrix<float, 4, 1, 0, 4, 1> const&, Eigen::Quaternion<float, 0> const&)", referenced from:
      pcl::PCDWriter::write(std::string const&, sensor_msgs::PointCloud2_std::allocator<void > const&, Eigen::Matrix<float, 4, 1, 0, 4, 1> const&, Eigen::Quaternion<float, 0> const&, bool) in pcd_io.cpp.o
ld: symbol(s) not found for architecture x86_64

Scanning dependencies of target bag_to_pcd
[100%] Building CXX object CMakeFiles/bag_to_pcd.dir/tools/bag_to_pcd.cpp.o
Linking CXX executable /Users/DeFrenZ/ros_catkin_ws/devel_isolated/pcl_ros/lib/pcl_ros/bag_to_pcd
Undefined symbols for architecture x86_64:
  "pcl::PCDWriter::writeASCII(std::string const&, sensor_msgs::PointCloud2_std::allocator<void > const&, Eigen::Matrix<float, 4, 1, 0, 4, 1> const&, Eigen::Quaternion<float, 0> const&, int)", referenced from:
      pcl::PCDWriter::write(std::string const&, sensor_msgs::PointCloud2_std::allocator<void > const&, Eigen::Matrix<float, 4, 1, 0, 4, 1> const&, Eigen::Quaternion<float, 0> const&, bool) in bag_to_pcd.cpp.o
  "pcl::PCDWriter::writeBinary(std::string const&, sensor_msgs::PointCloud2_std::allocator<void > const&, Eigen::Matrix<float, 4, 1, 0, 4, 1> const&, Eigen::Quaternion<float, 0> const&)", referenced from:
      pcl::PCDWriter::write(std::string const&, sensor_msgs::PointCloud2_std::allocator<void > const&, Eigen::Matrix<float, 4, 1, 0, 4, 1> const&, Eigen::Quaternion<float, 0> const&, bool) in bag_to_pcd.cpp.o
ld: symbol(s) not found for architecture x86_64

**Comment by lzbones** [comment]
Try to use gcc/g++ instead of Clang? It works for me.

**Comment by LucidOne** [comment]
@DeFrenZ  Is this still an issue?
I'm thinking of closing this as wontfix, as it _sounds_ like an issue with Clang.

**Comment by LucidOne** [comment]
Please reopen this if you have more information or a pull request.
Thanks
