### ISSUE TITLE
NaN removal from RadiusOutlierRemoval

### ISSUE THREAD

**Issue by mjuels** [ros-perception/perception_pcl#164]
Using the ```RadiusOutlierRemoval``` nodelet I get the assertion error:

```
/build/pcl-1.7-K_Z193/pcl-1.7-1.7.1/search/include/pcl/search/impl/organized.hpp:57: int pcl::search::OrganizedNeighbor<PointT>::radiusSearch(const PointT&, double, std::vector<int>&, std::vector<float>&, unsigned int) const [with PointT = pcl::PointXYZ]: Assertion `isFinite (query) && "Invalid (NaN, Inf) point coordinates given to nearestKSearch!"' failed.
Aborted (core dumped)
```

As far as I can tell, this is due to NaN points in the cloud.
I have made a dummy node performing essentially the same operation, where the assertion can be removed using
```
pcl::removeNaNFromPointCloud()
```
prior to filtering.

Is there a deliberate point to not include nan-filtering in the nodelet?

**Comment by SteveMacenski** [comment]
Hi,
You're more likely to get help on library use from ROS Answers or reading the autogenerated docs. I'm going to close this ticket.

But to directly answer your question, yes that is intentional. All the filters assume nans to be gone
