### ISSUE TITLE
Deb package build?

### ISSUE THREAD

**Issue by catskul** [ros-perception/perception_pcl#17]
Is there a way to generate deb packages for perception_pcl? I didn't see any make targets.

**Comment by jkammerl** [comment]
Since ROS groovy, make targets are typically generated using catkin/cmake. 
http://www.ros.org/wiki/catkin

For the generate of debians from ROS packages, please have a look at bloom:
http://www.ros.org/wiki/bloom

**Comment by catskul** [comment]
Any options for fuerte? As I understand it, catkin and bloom are only available in groovy and beyond.

**Comment by jkammerl** [comment]
hm.. not sure. You may find some information here: http://www.ros.org/wiki/release/Releasing

**Comment by tfoote** [comment]
There's a large build pipeline, which is not designed to be easily
replicated.  You fan find find the script template at:
https://github.com/ros-infrastructure/buildfarm/blob/master/buildfarm/resources/templates/dry_release/build.sh.em
but
there's a lot of infrastructure setup which is not documented, and this is
deprecated so it won't be claned up or documented.

If you just want to build debs there are tarballs here which can be
manually turned into debs at
https://code.ros.org/svn/release/download/stacks/perception_pcl/

**Comment by catskul** [comment]
Thanks for the info. Was hoping to be able to build the fix for the SSE/AVX issue with a good way to distribute to multiple team members. Probably better to wait for the fix to land in the repo instead.
