### ISSUE TITLE
manifest.xml causing compile errors in dependent package (fuerte/Precise)

### ISSUE THREAD

**Issue by catskul** [ros-perception/perception_pcl#18]
Not sure if this is a wont fix since fuerte stuff is being deprecated, but...

Building a dependent package I get the following:

``` term
# VERBOSE=1 make
mkdir -p bin
cd build && cmake -Wdev -DCMAKE_TOOLCHAIN_FILE=`rospack find rosbuild`/rostoolchain.cmake  ..
Re-run cmake no build system arguments
[rosbuild] Building package package_name_redacted
[rosbuild] Cached build flags older than manifests; calling rospack to get flags
Failed to invoke /opt/ros/fuerte/bin/rospack cflags-only-I;--deps-only package_name_redacted
[rospack] Warning: ignoring duplicate cpp tag in export block
CMake Error at /usr/lib/vtk-5.8/VTKTargets.cmake:16 (ADD_EXECUTABLE):
  Command add_executable() is not scriptable
Call Stack (most recent call first):
  /usr/lib/vtk-5.8/VTKConfig.cmake:231 (INCLUDE)
  /usr/share/cmake-2.8/Modules/FindVTK.cmake:73 (FIND_PACKAGE)
  /home/username_redacted/tmp/perception_pcl/pcl/vtk_include.cmake:1 (find_package)


CMake Error at /opt/ros/fuerte/share/ros/core/rosbuild/public.cmake:129 (message): 

  Failed to invoke rospack to get compile flags for package
  'package_name_redacted'.  Look above for errors from rospack itself.
  Aborting.  Please fix the broken dependency!

Call Stack (most recent call first):
  /opt/ros/fuerte/share/ros/core/rosbuild/public.cmake:227 (rosbuild_invoke_rospack)
  CMakeLists.txt:13 (rosbuild_init)
```

I found this which seems to be the same problem from a year ago:
https://code.ros.org/trac/ros-pkg/ticket/5243

Unfortunately the patch doesn't work completely on the current version.

I was able to get around the problem by commenting out the contents of `vtk_include.cmake` and `vtk_library.cmake` and replacing them with hard coded `MESSAGE( "/usr/include/vtk-5.8" )` and the like.

**Comment by catskul** [comment]
Other reports of the same issue:

http://answers.ros.org/question/64501/pcl-error-in-ros-fuerte/

**Comment by abencz** [comment]
Not sure what happened here, but from 1.2.3 to 1.2.4 perception_pcl ballooned from 14MB to 159 MB:

```
-rw-r--r-- 1 abencz abencz  14M Jun 11 11:36 ros-fuerte-perception-pcl_1.2.3-s1367556503~precise_amd64.deb
-rw-rw-r-- 1 abencz abencz 159M Jun  1 03:22 ros-fuerte-perception-pcl_1.2.4-s1370068469~precise_amd64.deb
```

Is this related to the build problems?

Note that this breaks building most packages that depend on pcl :(

**Comment by jkammerl** [comment]
The current release is directly based on the 1.2.3 tar ball of the source deb:
https://code.ros.org/svn/release/download/stacks/perception_pcl/perception_pcl-1.2.3/ 

Maybe the source deb was not in sync with the binary deb?! @tfoote, @wjwwood: Any idea?

**Comment by catskul** [comment]
This is actually a big problem. It seems that the latest perception_pcl includes pcl inside it unlike the previous version. Further, the version of pcl that it includes is pcl-1.4. This conflicts with the fuerte installed pcl version 1.5 and the result is build breaks. In my case I had to manually remove the pcl directory from /opt/ros/fuerte/stacks/percpetion_pcl/pcl to solve my problem.

**Comment by tigershadowclaw** [comment]
I was having the same issue and moving the pcl folder seems to have fixed it.  (its compiling right now).

Thank you for saving me a lot of headaches Catskul!

**Comment by wjwwood** [comment]
So @catskul and @jkammerl would you agree that the action to be taken is to remove `pcl` from `perception_pcl` in `fuerte` and release it again?

**Comment by catskul** [comment]
As far as I know, that solves all the problems I've run into. The only think I'd be afraid of would be that it was somehow dependent specifically on 1.4.

**Comment by jkammerl** [comment]
I removed the pcl folder and triggered a rerelease. Please reopen this issue if there are still problems with this release.

**Comment by georgebrindeiro** [comment]
thanks! moving the pcl folder (<tt>/opt/ros/fuerte/stacks/percpetion_pcl/pcl</tt>) out of the way did the trick for me.
