### ISSUE TITLE
Release for ROS melodic

### ISSUE THREAD

**Issue by hrnr** [ros-perception/perception_pcl#189]
This is quite a core stack, it would be nice to have this released early, so we could test applications on melodic.

**Comment by mikaelarguedas** [comment]
It seems that this is [currently blocked](http://repositories.ros.org/status_page/blocked_releases_melodic.html?q=perception_pcl&s=6&r=1) by the fact that `pcl_conversions` has not been released yet (https://github.com/ros-perception/pcl_conversions/issues/28)

**Comment by wkentaro** [comment]
I commented to request the maintainer for release: https://github.com/ros-perception/pcl_conversions/issues/28#issuecomment-384687756.
And I added the test on Travis (#190) to check if current default branch (lunar-devel) can be released.
(but currently we're sure it fails because of unreleased `ros-melodic-pcl-conversions`.)

**Comment by paulbovbel** [comment]
Moved pcl_conversions to this repo (https://github.com/ros-perception/pcl_conversions/issues/28).

We need to make sure to sync up version numbers across packages to 1.6.0 on release into melodic.

**Comment by wkentaro** [comment]
Can I release the same code to lunar, kinetic, and indigo for sync as 1.5.5, 1.4.4 and 1.2.10?

**Comment by paulbovbel** [comment]
We shouldn't release the same code-line for the other distros. At the very least, moving the location of the pcl_conversions package will make things messy.

We can backport features as necessary/desired to older *-devel branches, and cut releases from there.

**Comment by wkentaro** [comment]
Ok, I see. Thanks!

**Comment by wkentaro** [comment]
Can I close this?
the PR to rosdistro was merged: https://github.com/ros/rosdistro/pull/17673

**Comment by paulbovbel** [comment]
Yes, thanks!
