### ISSUE TITLE
color incorrect by convert_pointcloud_to_image

### ISSUE THREAD

**Issue by isbdnt** [ros-perception/perception_pcl#205]
the color of the model is orange, but the converted color is blue.
![image](https://user-images.githubusercontent.com/26591233/39966151-916e3bd2-56d9-11e8-92db-b65d832bb407.png)
![image](https://user-images.githubusercontent.com/26591233/39966155-9d45652a-56d9-11e8-8518-52f8b0f9b8e3.png)

**Comment by isbdnt** [comment]
this might be a issue of libgazebo_ros_openni_kinect.so. I printed out the PointXYZRGB from the topic published by libgazebo_ros_openni_kinect.so. the rgb field seems wrong.

**Comment by wkentaro** [comment]
> this might be an issue of libgazebo_ros_openni_kinect.so. I printed out the PointXYZRGB from the topic published by libgazebo_ros_openni_kinect.so. the rgb values seemed wrong.

Yeah, I think so. Could you open an issue in https://github.com/ros-simulation/gazebo_ros_pkgs and close this issue?

**Comment by SteveMacenski** [comment]
Closing, not a PCL Perception issue.
