### ISSUE TITLE
Fix VTK issue caused by `find_package(PCL COMPONENTS io)`

### ISSUE THREAD

**Issue by wkentaro** [ros-perception/perception_pcl#208]
## Related Issues

- https://github.com/ros-perception/perception_pcl/pull/207
- https://github.com/ros-perception/perception_pcl/issues/172
- https://github.com/ros-perception/perception_pcl/issues/206

**Comment by SteveMacenski** [comment]
@wkentaro marked as wontfix, I take that to mean this ticket can be closed.
