### ISSUE TITLE
Converting between pcl and ROS classes

### ISSUE THREAD

**Issue by sdmiller** [ros-perception/perception_pcl#21]
As per discussions on the pcl mailing list  (http://www.pcl-developers.org/Separating-pcl-and-ROS-td5707911.html) and github (https://github.com/PointCloudLibrary/pcl/pull/110), we're looking to get rid of ROS/pcl conflicts. That means PointCloud2, Header, Image, and PointField will no longer directly be used in pcl. 

To make this easier on ROS users, it'd be great to have code which converts between the two formats. I'm happy to write it (the two classes are almost identical), but since I'm not an active pcl_ros user, it might make more sense for someone on this end to write and test it. Or, if nothing else, let me know where and how you'd find migration code the most convenient. 

You can find the new headers at http://stanford.edu/~sdmiller/dropbox/new_pcl_headers.tar.gz

**Comment by jkammerl** [comment]
Unfortunately, I don't have the resources to work on this right now. Maybe within the next week.. If anyone out there is interested in contributing a pcl-ros conversion header, it would be greatly appreciated! @MichaelKorn, your previous pcl-ROS contributions were all great! Would you be interested in helping us? Thanks!

**Comment by MichaelKorn** [comment]
At the moment I don't have enough time, sorry. Maybe in two week, but not sooner.

**Comment by wjwwood** [comment]
I might have some time to help with this. Is that link to the headers the only thing we have to work with right now?

Is there a preview version of PCL which I can build these conversions against?

Is there a complete list of classes which should be convertible?

**Comment by jkammerl** [comment]
Awesome! Thanks a lot @wjwwood for offering help! 

As far as I know we need copy constructors to convert between these classes:
sensor_msgs::Image <-> pcl_sensor_msgs::PCLImage
sensor_msgs::PointField <-> pcl_sensor_msgs::PCLPointField
sensor_msgs::PointCloud2 <-> pcl_sensor_msgs::PCLPointCloud2
std_msgs::Header <-> pcl_std_msgs::PCLHeader

@sdmiller, @rbrusu did I forget any  conversion?

**Comment by sdmiller** [comment]
Great! Julius is correct, those are the only conversions we need.

There is a complete fork of PCL which makes the switch at
https://github.com/sdmiller/pcl/tree/remove_ros. I posted the headers
solely for convenience.

**Comment by rbrusu** [comment]
Do we wanna call then pcl_sensor_msgs? Why not bring them into the pcl namespace?

**Comment by wjwwood** [comment]
@rbrusu I'll start the conversion package today, just let me know if you guys decide to change the namespaces.

**Comment by sdmiller** [comment]
@rbrusu I'm up for either. I changed it to make the migration as obvious as
possible for anyone getting compiler warnings. But fixing it is as easy as
a call to sed.

**Comment by wjwwood** [comment]
Is this supposed to be in nanoseconds?

https://github.com/sdmiller/pcl/blob/remove_ros/common/include/pcl_std_msgs/PCLHeader.h#L22

**Comment by wjwwood** [comment]
So we had a talk internally here at OSRF about performance and these data types. This is currently the plan (I'll use `PCLImage` and the ROS version of `Image` in examples):

**Provide custom serializer for `PCLImage` to `Image`'s wire format:**

This allows users to create a ROS publisher of type `PCLImage` but which identifies as a ROS `Image` to potential subscribers. When moving the message from `publisher<PCLImage>` to `subscriber<PCLImage>` in the same process (nodelets and loop back topics) the pointer is passed along without serialization. Between `publisher<PCLImage>` and `subscriber<Image>` the `PCLImage` is serialized and then deserialized into the `Image` message, even with in a single process. This kind of solution already exists for `PCL::PointCloud` and `PointCloud2`. I will be implementing these types tomorrow.

**Provide copy conversion functions:**

These are functions like:

``` c++
void fromPCLImageToImage(const pcl_sensor_msgs::PCLImage &pcl_image, sensor_msgs::Image &image)
```

which copies the data from one format to the other. These conversions provide ownership of the data at the expense of copying it. I have already implemented these functions.

I don't know of a way to provide a conversion which does not copy the data (mostly due to the use of std::vector), but I am open to suggestion on that. The std::vector's with the move semantic would be potentially useful here, but that's only in c++11.

**Comment by sdmiller** [comment]
Hi William,

Here's the code used throughout PCL for converting the time stamps:

ros_header.stamp.fromNSec (pcl_timestamp \* 1000);

So it looks like it's in microseconds.

**Comment by wjwwood** [comment]
I have a minimally complete package setup here:

https://github.com/ros-perception/pcl_conversions

I considered merging those conversions into the `pcl_ros` package, but I thought some people might want to depend on just the conversions and not the other stuff which comes with `pcl_ros`.

@sdmiller I have updated my code to reflect that.

I have a local devel branch where I am still testing the custom serializers. I will push that when it is ready.

I haven't had much time to spend writing and testing this package, so some review from you guys would be helpful.

**Comment by wjwwood** [comment]
Also, should this `pcl_conversions` package bring in the set of conversions implemented here:

https://github.com/PointCloudLibrary/pcl/blob/master/common/include/pcl/ros/conversions.h#L167

So that users can jump directly to `pcl::PointCloud<PointT>` from `sensor_msgs::PointCloud2` (and vice versa) rather than converting to `pcl_sensor_msgs::PCLPointCloud2` in between?

**Comment by sdmiller** [comment]
@wjwwood Great! I've checked out the repository and it seems totally reasonable, but without a ROS application I can't weigh in on performance. It looks like exactly what I had in mind. As far as porting pcl/conversions.h -- that seems reasonable, though it does mean duplicating a bit of code. It's probably worth it for reducing the memory overload -- don't know if @jkammerl wants to weigh in here.

Minor suggestion: it might be easier to just have overloaded "toPCL" and "fromPCL" functions, as the long names could get a bit clunky.

**Comment by jspricke** [comment]
+1 for pcl_sensor_msgs:: -> pcl:: (although this belongs into the pcl ticket).
+1 for from/toPCL.

Could we overload the cast operator and make the conversion transparent to the user (just adding the header should be enough..)?

What would be the use of adding the conversions.h? As for PCL1 we will stick with ::PointCloud2, so we need them anyhow (maybe we could change the name at some point).

**Comment by wjwwood** [comment]
I'll update the function names.

I can add operator overloading for assignment and casting.

> What would be the use of adding the conversions.h? As for PCL1 we will stick with ::PointCloud2, so we need them anyhow (maybe we could change the name at some point).

conversions.h now does the conversions, for example, PCL::PointCloud -> pcl_sensor_msgs::PCLPointCloud2. Then ROS users may need to convert pcl_sensor_msgs::PCLPointCloud2 -> sensor_msgs::PointCloud2. Each of those incurs a copy of the data. Without migrating the conversions.h code out of PCL (to somewhere it has access to ROS messages) it cannot directly convert from PCL::PointCloud -> sensor_msgs::PointCloud2.

This is how I see it, unless I am missing something, which maybe the case.

**Comment by wjwwood** [comment]
Actually, I don't think I can do the cast operator overloading without some sort of global hook into each class. This would not be a clean thing to do. As far as I know you cannot overload the cast operator outside of the class so I would say we shouldn't do that. If someone disagrees then I would love some help implementing that one.

**Comment by wjwwood** [comment]
I have updated the function names.

**Comment by jspricke** [comment]
- William Woodall notifications@github.com [2013-06-28 11:22]:
  > conversions.h now does the conversions, for example, PCL::PointCloud -> pcl_sensor_msgs::PCLPointCloud2. Then ROS users may need to convert pcl_sensor_msgs::PCLPointCloud2 -> sensor_msgs::PointCloud2. Each of those incurs a copy of the data. Without migrating the conversions.h code out of PCL (to somewhere it has access to ROS messages) it cannot directly convert from PCL::PointCloud -> sensor_msgs::PointCloud2.

Sounds good. (I was thinking of something else with my last comment,
sorry.)

Cheers Jochen

**Comment by wjwwood** [comment]
This is done via the `pcl_conversions` package.
