### ISSUE TITLE
row_step bug in concatenatePointCloud 

### ISSUE THREAD

**Issue by zhixuan-wei** [ros-perception/perception_pcl#211]
In the function `concatenatePointCloud` of `pcl_conversions.h`, row_step of output is wrong.

Right now it is: `row_step of output = row_step of cloud1`.

I think the right one is: `row_step of output = row_step of cloud1 + row_step of cloud2`

**Comment by Aposhian** [comment]
This results in a warning in Foxglove Studio now, since (width * point_step) != row_step. Since `concatenatePointCloud` flattens the pointclouds (sets height to 1), I think the actual output should be `row_step = data.size()`

**Comment by SteveMacenski** [comment]
Merged
