### ISSUE TITLE
Can we make pcd_to_pointcloud publish once using a latched topic instead?

### ISSUE THREAD

**Issue by moooeeeep** [ros-perception/perception_pcl#212]
I want to publish a large, never changing pointcloud. Currently, with `pcd_to_pointcloud`, the pointcloud is only published once, which means that I have to relaunch the node whenever the node that processes it restarts. I find this inconvenient. 

Luckily the fix is easy. Just make the publisher advertise to latch the topic. Maybe I can make a PR later.

Any opinions on this?

**Comment by paulbovbel** [comment]
That sounds reasonable, PRs welcome
