### ISSUE TITLE
ERROR: cannot launch node of type [pointcloud_to_laserscan/pointcloud_to_laserscan]: can't locate node [pointcloud_to_laserscan] in package [pointcloud_to_laserscan]

### ISSUE THREAD

**Issue by q8wwe** [ros-perception/perception_pcl#218]
I'm using pointcloud_to_laserscan on gazebo simulation but i got the below error:-

ERROR: cannot launch node of type [pointcloud_to_laserscan/pointcloud_to_laserscan]: can't locate node [pointcloud_to_laserscan] in package [pointcloud_to_laserscan]

my system ros kinetic

**Comment by christenbc** [comment]
you have to git clone also this http://wiki.ros.org/tf2_sensor_msgs and do catkin_make

**Comment by paulbovbel** [comment]
Please work through the ROS workspace tutorials, and then point usage questions to ROS answers
