### ISSUE TITLE
No rule to make target

### ISSUE THREAD

**Issue by a-clare** [ros-perception/perception_pcl#220]
I am trying to build this package from source, cloned it into my workspace. When I run **catkin_make** in catkin_ws I get:

make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libpcl_common.so', needed by '/home/adam/catkin_ws/devel/lib/pcl_ros/convert_pointcloud_to_image'.  Stop.

However the file exists:
stat /usr/lib/x86_64-linux-gnu/libpcl_common.so
  File: /usr/lib/x86_64-linux-gnu/libpcl_common.so -> libpcl_common.so.1.8
  Size: 20        	Blocks: 0          IO Block: 4096   symbolic link
Device: 804h/2052d	Inode: 2770690     Links: 1
Access: (0777/lrwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2019-01-31 10:05:41.408792284 -0700
Modify: 2018-09-10 00:22:16.000000000 -0600
Change: 2019-01-30 09:48:45.358051267 -0700

Any suggestions?
I am running ubuntu 18.04, gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0, cmake version 3.10.2

**Comment by paulbovbel** [comment]
None, sorry. Can't really give you any advice without further information about your environment, workspace, or what command you're running.

**Comment by a-clare** [comment]
> None, sorry. Can't really give you any advice without further information about your environment, workspace, or what command you're running.

I added some more information on my environment. Not sure what other information you require, let me know and I can provide it.

**Comment by SteveMacenski** [comment]
@AdamTheCanadian is this still a concern?

**Comment by SteveMacenski** [comment]
Closing, if still an issue feel free to comment and I'll reopen if still an issue.
