### ISSUE TITLE
Using pcl::transformPointCloud with melodic and tf2

### ISSUE THREAD

**Issue by Patrick-Lascombe** [ros-perception/perception_pcl#222]
Hello everyone,

I'm trying to use the function pcl::transformPointCloud function in melodic and so with tf2, but it seem that the only type of transform accepted are : 
- tf::TransformListener
- tf::Transform
http://docs.ros.org/melodic/api/pcl_ros/html/namespacepcl__ros.html#aad20af010640a41f1898e75f6a6121ad

Do you have any idea on how to use this function with tf2 ?

Thanks for your help !

**Comment by peci1** [comment]
You can work around this using Eigen transform matrix. However, I also don't feel like this is the Melodic way of doing things...

    #include <tf2_eigen/tf2_eigen.h>
    const auto scan_tf = tf_buffer.lookupTransform(robot_frame,
         scan.header.frame_id, scan.header.stamp, ros::Duration(1));
     point_cloud.header.frame_id = robot_frame;
     pcl_ros::transformPointCloud(
         tf2::transformToEigen(scan_tf.transform).matrix(),
         scan, point_cloud);

**Comment by peci1** [comment]
Depends on #171 ,

**Comment by paulbovbel** [comment]
Sorry I didn't respond earlier. You're right, this is a bit of a mess. `tf2` operates on ROS message types, and has native support for `sensor_msgs::PointCloud2` via https://github.com/ros/geometry2/blob/melodic-devel/tf2_sensor_msgs/include/tf2_sensor_msgs/tf2_sensor_msgs.h

**Comment by peci1** [comment]
This certainly is an option, but there still are the classes `tf2::Transform` etc. which might be present in this API, couldn't they?

**Comment by paulbovbel** [comment]
absolutely, or perhaps more usefully the `tf2::doTransform` API could be defined for the pcl::PointCloud types.

**Comment by peci1** [comment]
Solution proposed in https://github.com/ros-perception/perception_pcl/pull/231 .

**Comment by atyshka** [comment]
This was merged in April but I still don't see the new functions in the latest melodic binaries...

**Comment by SteveMacenski** [comment]
That makes sense https://github.com/ros/rosdistro/blob/master/melodic/distribution.yaml#L5575 that release didn't make it to bloom.

~I can take care of it~

Edit: lies, I dont have access to ROS1's release org. @paulbovbel  I'll trade you 2 `pcl_msgs` bloom runs for 1 `perception_pcl` run on the 1.7.0 you already tagged but didnt bloom up

**Comment by paulbovbel** [comment]
Sure thing. Just for sanity, @mjcarroll, could we please add Steve to PCL Team in ros-gbp?

**Comment by mjcarroll** [comment]
I believe that I lack the power there, I'll ping someone who can.

**Comment by nuclearsandwich** [comment]
Invite dispatched.

**Comment by SteveMacenski** [comment]
Oh hi, got that email out of the blue and didn't know why I was added. 

Cool :+1:

**Comment by atyshka** [comment]
Thanks for working on this! ROS Index said the version was updated to 1.7 on Oct 16 but Ubuntu 18.04 apt still has 1.6.2 as latest version. Is the ubuntu PPA only updated periodically?

**Comment by SteveMacenski** [comment]
The last sync was about 3 weeks ago, it'll be a few more weeks before the next Melodic sync

**Comment by peci1** [comment]
@atyshka Watch https://github.com/ros/rosdistro/pull/22689 . Once it's merged, wait for CI job http://build.ros.org/job/Mbin_uB64__perception_pcl__ubuntu_bionic_amd64__binary/ to re-run. When it finishes, the built .deb files will be uploaded into the shadow-fixed repo: http://packages.ros.org/ros-shadow-fixed/ubuntu/pool/main/r/ros-melodic-perception-pcl/ . And a few weeks later they will become available for everyone (when the so called "Melodic sync" happens, which will be announced on discourse.ros.org).

If you don't want to wait for the melodic sync and also don't want to add the whole shadow-fixed repo to your system, you can download the .deb files from shadow-fixed web and install them manually via `sudo dpkg -i package.deb`.
