### ISSUE TITLE
Bug in transform.hpp?

### ISSUE THREAD

**Issue by PetrichSchmoin** [ros-perception/perception_pcl#228]
Hello everyone,

is there a bug in setting the `frame_id` of the output cloud in transform.hpp? I always get an empty `frame_id` for the output cloud when I call `transformPointcloud(..)`

In the transform.hpp at the lines [183 to 186](https://github.com/ros-perception/perception_pcl/blob/a8ba2c790db5db181725606649e1fc7c776c1ffd/pcl_ros/include/pcl_ros/impl/transforms.hpp#L183) (and [216 - 219](https://github.com/ros-perception/perception_pcl/blob/a8ba2c790db5db181725606649e1fc7c776c1ffd/pcl_ros/include/pcl_ros/impl/transforms.hpp#L216))
```
  cloud_out.header.frame_id = target_frame;  // <-- here the frame is set
  std_msgs::Header header;
  header.stamp = target_time;
  cloud_out.header = toPCL(header); // <-- and will be overwritten here by an empty frame_id
```

Can anybody confirm this?

My setup:
Ubuntu 16.04
ROS Kinetic 
PCL 1.7

**Comment by LucidOne** [comment]
I updated your post with links to the code, as I understand it.
This looks like a bug, and it should also be an easy unit test to write.
PRs as always are appreciated.

**Comment by LucidOne** [comment]
The test should be something like [this](https://github.com/ros-perception/perception_pcl/blob/melodic-devel/pcl_conversions/test/test_pcl_conversions.cpp)

**Comment by PetrichSchmoin** [comment]
I don't have much time to spend at the moment. Maybe I can try to fix it next month if no one else fixed it until then.

**Comment by SteveMacenski** [comment]
@PetrichSchmoin any update? I would merge that PR pretty quickly

**Comment by mvieth** [comment]
I created a PR. There is no unit test, but the problem itself should be fixed.
