### ISSUE TITLE
catkin_make error 

### ISSUE THREAD

**Issue by npd26** [ros-perception/perception_pcl#230]
hello,

I am trying to use 

> perception_pcl

 package for realsense camera.

> ROS: kinetic
> Ubuntu: 16.04

after cloning package when I try to run catkin_make it is giving me errors like,

`this file require compiler and library support for the ISO c++ 2011 standard.`

`std::this_thread has not been declared`

`std::chrono has not been declared`

how to solve this?

thanks.

**Comment by LucidOne** [comment]
Please run `git branch` and check that you are using `kinetic-devel` or upgrade [gcc](https://gcc.gnu.org/wiki/C11Status) if you are attempting to backport `melodic-devel`.

**Comment by npd26** [comment]
@LucidOne I am using git - kinetic devel but still not working. same error.

**Comment by LucidOne** [comment]
Can you check that your copy [matches](https://github.com/kejxu/perception_pcl/blob/kinetic-devel/pcl_ros/tools/pcd_to_pointcloud.cpp)? What file references `std::chrono`?

**Comment by npd26** [comment]
so, directly downloading zip file for kinetic-devel worked.
