### ISSUE TITLE
[pcl::PCDReader::readHeader] Invalid COUNT value specified

### ISSUE THREAD

**Issue by Dinatorehanova** [ros-perception/perception_pcl#237]
Hi,

When I am trying to convert my PCD file coming out from the bag file into las file using PDAL, I am getting this error like

[pcl::PCDReader::readHeader] Invalid COUNT value specified

But when I am applying this onto the pcd file coming out of the(pointcloud to pcd tool) it works fine.

Can anyone please tell me how to resolve this issue? And is there any tool available that will merge many pcd files into a single one?

Thanks

**Comment by likegogogo** [comment]
@Dinatorehanova  have you solve this problem?
