### ISSUE TITLE
pointcloud mesage to las file

### ISSUE THREAD

**Issue by ethan20120** [ros-perception/perception_pcl#246]
Hi,

Is there any tool available which directly converts the rosbag point cloud message into las file ?

And how I can run the tools of this repository(e.g. bag to pcd). I have cloned the github.Can anyone please guide me how to use the tools of this github on my ros bag ?

Thanks

**Comment by SteveMacenski** [comment]
Hi,
Thanks for the question but your more likely to get help on ROS Answers than here. Closing this ticket
