### ISSUE TITLE
Running node which uses groovy-unstable-devel brings CAIRO_STATUS_SUCCESS' failed

### ISSUE THREAD

**Issue by manox** [ros-perception/perception_pcl#25]
Hi,

when i use the groovy-unstable-devel branch of PCL for my projects, i always get the following after starting a node that uses PCL:

AssertionMessage: claws-mail: /build/buildd/cairo-1.10.2/src/cairo-surface.c:1287: cairo_surface_set_device_offset: Assertion `status == CAIRO_STATUS_SUCCESS' failed.

Sorry, im not very familiar with ros and that stuff.

**Comment by MichaelKorn** [comment]
You should improve your issue description.
This problem isn't only related to PCL, but also affects many other:
https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/887850

**Comment by wjwwood** [comment]
Closing, comment if it is still an issue.
