### ISSUE TITLE
Cant find VTK header

### ISSUE THREAD

**Issue by geoeo** [ros-perception/perception_pcl#257]
I dont know what happend. But after I did a (seemingly innocent) ubuntu live update my ros project wont compile.

The CMAKE error is as follows : 

`Project 'pcl_conversions' specifies '/usr/include/vtk-6.3' as an include dir, which is not found. It does neither exist as an absolute directory
  nor in
  'catkin_ws/src/perception_pcl/pcl_conversions//usr/include/vtk-6.3'.`

**Comment by tomaszkaliciak** [comment]
@geoeo, what was the problem?

**Comment by oguzhancebe** [comment]
I also get the following error on ROS Noetic
`CMake Error at /opt/ros/noetic/share/pcl_ros/cmake/pcl_rosConfig.cmake:113 (message):
  Project 'pcl_ros' specifies '/usr/include/vtk-7.1' as an include dir, which
  is not found.  It does neither exist as an absolute directory nor in
  '${{prefix}}//usr/include/vtk-7.1'. `
