### ISSUE TITLE
dont support pcl-1.9 ???

### ISSUE THREAD

**Issue by chennuo0125-HIT** [ros-perception/perception_pcl#259]
/home/ubuntu/catkin_ws/src/perception_pcl/pcl_ros/include/pcl_ros/point_cloud.h:79:37: error: no match for ‘operator=’ (operand types are ‘std::shared_ptr<std::vector<pcl::detail::FieldMapping> >’ and ‘boost::shared_ptr<std::vector<pcl::detail::FieldMapping> >’)
       pcl::detail::getMapping(*msg) = mapping_;

**Comment by SteveMacenski** [comment]
Can you please add some detail on what's going on.

Posting a question and what appears to be an error next to a line of code doesn't really give much context or ability to assist .

**Comment by chennuo0125-HIT** [comment]
my system is ubuntu kinetic. i want to compile a pkg depended on pcl_ros pkg, but i encounter error as follows:
![pcl_ros_1](https://user-images.githubusercontent.com/37269147/71659472-b3936080-2d82-11ea-9ae5-ab8a96f4a7ad.png)
the error maybe is caused by that i have installed pcl-1.9.1, so i want to install pcl_ros by source code, but i encounter another problem as follows:
![pcl_ros_2](https://user-images.githubusercontent.com/37269147/71659714-85fae700-2d83-11ea-83bf-50f273203795.png)

**Comment by SteveMacenski** [comment]
The officially supported PCL version for Kinetic is 1.7.x (https://www.ros.org/reps/rep-0003.html#kinetic-kame-may-2016-may-2021) 

[This](https://github.com/ros-perception/perception_pcl/pull/258) PR would probably fix your issue. 1.9 has API changes that are incompatible with this package in Kinetic.

**Comment by taketwo** [comment]
It appears that you have installed PCL from the `master` branch, i.e. not `1.9.1`, but rather `1.9.1-dev`. It is indeed incompatible with this package. Your options are either apply this patch or install released PCL 1.9.1.

**Comment by SteveMacenski** [comment]
Closing from solution provided by @taketwo
