### ISSUE TITLE
provide a migration path so client code can support both Hydro and Groovy

### ISSUE THREAD

**Issue by jack-oquin** [ros-perception/perception_pcl#26]
Most of this can be done with `#ifdef` tests in the client code. 

But, there is least one problem with that: the new Hydro version requires `pcl_conversions`, which did not exist before. We need some way to make that dependency conditional and testable within client code.

One idea is for the Hydro version of `pcl_ros` to depend on `pcl_conversions`. That dependency could be removed in Indigo as a tick-tock update. 

Existing clients already depend on `pcl_ros`. Maybe they could do some kind of conditional `find_package()` and test the result. Then, clients could only use that dependency when PCL 1.7 is present. I don't understand all the details, yet.

Perhaps there is a better solution. I am still trying to figure out how to deal with this problem. See: ros-drivers/velodyne#11.

**Comment by wjwwood** [comment]
I don't think that this is the correct way to do this.

An alternative would be to release a version of `pcl_conversions` into groovy which basically does nothing, i.e. leave the header, but wrap all of the contents in a `#if pcl >= 1.7` macro.

I could even provide a dummy `pcl_conversions::to/fromPCL` for headers which in groovy will take this signature:

```
void toPCL(const std_msgs::Header &header, std_msgs::Header &pcl_header) {}
void fromPCL(const std_msgs::Header &pcl_header, std_msgs::Header &header) {}
```

That way you won't have to check for pcl 1.7 in your package. You can depend on `pcl_conversions` and always use `to/fromPCL`, but it will only do something when it is pcl >= 1.7.

**Comment by jack-oquin** [comment]
That sounds like a much better solution to me, William, especially with the ability to back-port the new code cleanly to Groovy.

Should I close this and replace it with a new pcl_conversions issue?

**Comment by wjwwood** [comment]
You can if you wish, I'll look into implementing that today.

**Comment by jack-oquin** [comment]
OK, thanks. I'll be happy to help with testing.
