### ISSUE TITLE
missing exported dependency breaks downstream packages on hydro

### ISSUE THREAD

**Issue by dirk-thomas** [ros-perception/perception_pcl#27]
While pcl_ros exposes pcl_conversions headers it does not export it as a CATKIN_DEPENDS.

The list of other packages not being part of CATKIN_DEPENDS is long but I don't know if that is correct or if some of them are also missing. Adding pcl_conversions here (https://github.com/ros-perception/perception_pcl/blob/hydro-devel/pcl_ros/CMakeLists.txt#L39) made the isolated build work for me.

**Comment by wjwwood** [comment]
Fixed in a0de2e66dbc798d9348a52100ec6302b094918cd
