### ISSUE TITLE
Octomap to PointCloud conversions

### ISSUE THREAD

**Issue by coxep** [ros-perception/perception_pcl#281]
I have a possible PR for converting occupied voxels of binary octomap_msgs::octomap messages to PCL pointclouds. Is this something that would be of any interest?

If so, where would be the best place for this to live? I looked at `pcl_conversions`, and it seems to deal exclusively with one-to-one conversions between analogous ROS and PCL types. Perhaps `io` or `filters`?

If this isn't of interest, no worries.

**Comment by SteveMacenski** [comment]
Perhaps Octomap ROS? https://github.com/OctoMap/octomap_ros? Here could also work.

**Comment by coxep** [comment]
OK, thank you.
