### ISSUE TITLE
How to use high version pcl in ros

### ISSUE THREAD

**Issue by Jxpenggf** [ros-perception/perception_pcl#284]
My computer is pcl1.10, but when I use pcl_ros the following occurs：
  Project 'pcl_ros' specifies '/usr/include/pcl-1.7' as an include dir, which
  is not found.  It does neither exist as an absolute directory nor in
  '${{prefix}}//usr/include/pcl-1.7'.

**Comment by SteveMacenski** [comment]
For each ROS distribution, per [REP 103](https://www.ros.org/reps/rep-0003.html), we only officially support 1 PCL version. If you'd like to use another, you'll have to work through the issues. If its API compatible, you may just need to change the version to find in the CMakeLists. But going from 1.1 to 1.7 will likely have breaking issues that you must upgrade or use a very old branch of this and convert it over.

If you have any questions on how to set that up, please ask on ROS Answers
