### ISSUE TITLE
[fuerte] build error on Debian/AMD64

### ISSUE THREAD

**Issue by jkammerl** [ros-perception/perception_pcl#3]
ticket moved from https://code.ros.org/trac/ros-pkg/ticket/5585

I get a compilation error when trying to build the release 345, when using rosmake perception_pcl.

/opt/ros/fuerte/share/perception_pcl/pcl/build/pcl_trunk/tools/crop_to_hull.cpp:132:3: error: "ConcaveHull?" is not a member of "pcl"

**Comment by patrigg** [comment]
I had the same problem.

The solution for me was to install libqhull:
sudo apt-get install libqhull-dev

So this is not really a bug in the library

**Comment by ghost** [comment]
That solved the problem.
Thanks
