### ISSUE TITLE
License - Which BSD?

### ISSUE THREAD

**Issue by DanWillans** [ros-perception/perception_pcl#303]
Hi guys,

Could you tell me what version of the BSD license this package uses?

Thanks,
Dan

**Comment by DanWillans** [comment]
Hi guys,

Sorry to pester. Are there any updates?

Thanks,
Dan

**Comment by paulbovbel** [comment]
Looking at the headers, it looks to be the 3-clause BSD license

**Comment by DanWillans** [comment]
Thanks for the reply @paulbovbel :+1: I will come back and close this ticket.
