### ISSUE TITLE
pcl_rosConfig.cmake expects missing system install of libflann_cpp_s.a in precise

### ISSUE THREAD

**Issue by hsu** [ros-perception/perception_pcl#31]
In ubuntu precise (12.04), hydro packages compiled against `pcl_ros` fails because:

```
/opt/ros/hydro/lib/pkgconfig/pcl_ros.pc
/opt/ros/hydro/share/pcl_ros/cmake/pcl_rosConfig.cmake
```

looks for

```
/usr/lib/libflann_cpp_s.a
```

However, system install of `libflann-dev` does not provide a static version of the library in `/usr/lib`, it is found in

```
/usr/lib/x86_64-linux-gnu/libflann_cpp_s.a
```

This worked in groovy because

```
/opt/ros/groovy/lib/pkgconfig/pcl_ros.pc
/opt/ros/groovy/share/pcl_ros/cmake/pcl_rosConfig.cmake
```

depends on groovy custom package of static libflann library:

```
/opt/ros/groovy/lib/libflann_cpp_s.a
```

**Comment by wjwwood** [comment]
`pcl_rosConfig.cmake` is generated. I'll look at the `CMakeLists.txt` to see if it lends any clues.

**Comment by wjwwood** [comment]
This is most likely passed along incorrectly by PCL then, as `pcl_ros` does not directly depend on `flann`. See:

https://github.com/ros-perception/perception_pcl/blob/hydro-devel/pcl_ros/CMakeLists.txt#L78

I would look into the FindPCL.cmake or pcl-config.cmake files to see if this is where the issue comes from.

**Comment by hsu** [comment]
The bit in [PCLConfig](http://svn.pointclouds.org/pcl/trunk/PCLConfig.cmake.in) referring to `libflann` looks relevant:

```
    if("${FLANN_LIBRARY}" MATCHES "flann_cpp_s")
      set(FLANN_DEFINITIONS ${FLANN_DEFINITIONS} -DFLANN_STATIC)
    endif("${FLANN_LIBRARY}" MATCHES "flann_cpp_s")
```

**Comment by wjwwood** [comment]
I would use the git repo for referencing, I'm not sure if the SVN is up-to-date:

https://github.com/PointCloudLibrary/pcl/blob/master/PCLConfig.cmake.in

**Comment by hsu** [comment]
Found the problem, for some reason my system upgraded me to libflann-dev 1.8.4.  Downgrading to libflann 1.7.1 fixed this problem.
