### ISSUE TITLE
Release new update for perception_pcl

### ISSUE THREAD

**Issue by kunaltyagi** [ros-perception/perception_pcl#310]
The changes for compatibility with recent versions of PCL haven't been released yet (as per ros gbp). Is there any timeline for releasing an update?

**Comment by SteveMacenski** [comment]
Which distributions do you have in mind?

**Comment by kunaltyagi** [comment]
At least Ubuntu lts 20.04 and debian buster. I don't know how easy or difficult it'd be, so this is basically the minimum list. I'd add 18.04 too if it's possible

**Comment by SteveMacenski** [comment]
What distributions of ROS that have updates requiring a new bloom run, sorry.

**Comment by kunaltyagi** [comment]
noetic

**Comment by SteveMacenski** [comment]
Got it - done 

https://github.com/ros/rosdistro/pull/26968
