### ISSUE TITLE
cmake failed

### ISSUE THREAD

**Issue by CuteEric** [ros-perception/perception_pcl#317]
it cmake failed, with printing info as below in my pc:
pcl_ros/pcl_ros/include/pcl_ros/point_cloud.h:303:27: warning: variable templates only available with -std=c++14 or -std=gnu++14
     constexpr static bool pcl_uses_boost = true;
                           ^~~~~~~~~~~~~~
how to solve the problem?

**Comment by SteveMacenski** [comment]
Have you tried what it suggested?

**Comment by mzahana** [comment]
@CuteEric I am facing the same issue. I am using ROS melodic, Ubuntu 18, g++-7. I also tried g++-10, but I got the same error.
I am not sure what else to try. Any suggestions will be appreciated.

**Comment by mzahana** [comment]
@SteveMacenski I am facing the same issue. I was not able to solve it. Any suggestions are highly appreciated?
