### ISSUE TITLE
macro names must be identifiers

### ISSUE THREAD

**Issue by ybw-yang** [ros-perception/perception_pcl#322]
--- stderr: pcl_ros                               
<command-line>:0:1: error: macro names must be identifiers

**Comment by ybw-yang** [comment]
<command-line>:0:1: error: macro names must be identifiers
make[2]: *** [CMakeFiles/pcl_ros_tf.dir/src/transforms.cpp.o] Error 1
make[1]: *** [CMakeFiles/pcl_ros_tf.dir/all] Error 2
make: *** [all] Error 2
---
how to solve it?

**Comment by parkdg44** [comment]
I don't Know why this is work,
But just change PCL to remark in CMakeLists.txt like this, it works in my case.

set(dependencies
  pcl_conversions
  rclcpp
  sensor_msgs
  geometry_msgs
  tf2
  tf2_geometry_msgs
  tf2_ros
  EIGEN3
  #PCL  ## Change This Line !!!
)

**Comment by ybw-yang** [comment]
It's useful, thanks very much!

> I don't Know why this is work,
> But just change PCL to remark in CMakeLists.txt like this, it works in my case.
> 
> set(dependencies
> pcl_conversions
> rclcpp
> sensor_msgs
> geometry_msgs
> tf2
> tf2_geometry_msgs
> tf2_ros
> EIGEN3
> #PCL ## Change This Line !!!
> )
