### ISSUE TITLE
New release to Rolling?

### ISSUE THREAD

**Issue by wjwwood** [ros-perception/perception_pcl#324]
@mvieth @SteveMacenski we're preparing to fork rolling into galactic and we noticed there are several changes here on 'foxy-devel' that have not been released, https://github.com/ros-perception/perception_pcl/compare/2.2.0...foxy-devel.

Does anyone have time to do a release? Or if the changes are important, but you don't have time let us know and we can do a release on your behalf.

**Comment by mvieth** [comment]
Hi! I am actually not a maintainer for perception_pcl, so I do not have the permissions, but IMO a release would be great :smiley:

**Comment by SteveMacenski** [comment]
I think we'd happy to give you maintainer's permissions if you wanted to help maintain this project :wink: 

PCL ROS is still [largely unported](https://github.com/ros-perception/perception_pcl/blob/foxy-devel/pcl_ros/CMakeLists.txt) so I don't think it makes sense to release those changes into Foxy. I don't see that changing anytime soon until type masquerading is implemented and someone has a bunch of time to port it over and make it represent the current state of PCL. I'm on board for reviewing PRs getting that done, but I myself won't have time to work on it directly anytime in the immediate or foreseeable future.

PCL conversions hasn't changed significantly and is the main package in this repo for ROS2 at the moment.

**Comment by mvieth** [comment]
> I think we'd happy to give you maintainer's permissions if you wanted to help maintain this project

Thank you for the offer, but I'm already a maintainer of PCL, which takes up quite some time. I don't think I also have the time to maintain perception_pcl currently. I might work on issues from time to time, though.

**Comment by SteveMacenski** [comment]
In progress
