### ISSUE TITLE
Undefined behavior in point_cloud.h

### ISSUE THREAD

**Issue by richmattes** [ros-perception/perception_pcl#333]
The point cloud serialization code in `point_cloud.h` relies on undefined behavior when using `operator[]()` to access element 0 of a vector when the vector is empty, as implemented here (and potentially elsewhere):
https://github.com/ros-perception/perception_pcl/blob/bd21be2cb8ec6ad70a282c61b14aa9dd43edf9ff/pcl_ros/include/pcl_ros/point_cloud.h#L167

C++11 [added a data()](http://www.open-std.org/jtc1/sc22/wg21/docs/lwg-defects.html#464) method to `std::vector` to avoid this issue - `point_cloud.h` should be updated to use `.data()` instead of a reference to the first vector element to get data pointers from std::vectors.  Alternately, a size check should be performed before accessing `vector[0]`.

**Comment by SteveMacenski** [comment]
Sounds good - can you submit a PR?

**Comment by richmattes** [comment]
Any chance you can do a new release for melodic and noetic in the near term?  It looks like there have been a couple other PRs/fixes since 1.7.3

**Comment by SteveMacenski** [comment]
Sure thing, can't do at this moment but I'll mark this on my queue, hopefully next week.
