### ISSUE TITLE
How to use PCL 1.12 in noetic

### ISSUE THREAD

**Issue by stevalkr** [ros-perception/perception_pcl#338]
I've upgraded PCL to 1.12, but 1.7.3 release seems not compatible with it

**Comment by mvieth** [comment]
Please try with the current melodic-devel branch (self compiled), I think there are some changes that are not released yet.
(Side note: it would be more helpful if you actually describe the problem/error message, instead of just saying that it is not compatible)

**Comment by stevalkr** [comment]
Sorry to bother you and thank you for your solution
