### ISSUE TITLE
cmake errors using released version of pcl_ros in hydro

### ISSUE THREAD

**Issue by meyerj** [ros-perception/perception_pcl#34]
Hi,

I am currently getting the following cmake errors in packages using the binary pcl_ros package from the hydro repositories. I am using Ubuntu precise amd64. The current version is ros-hydro-pcl-ros 1.1.5-0precise-20130830-1312-+0000.

```
CMake Error at /opt/ros/hydro/share/pcl_ros/cmake/pcl_rosConfig.cmake:98 (message):
  Project 'pcl_ros' specifies '/usr/include/ni' as an include dir, which is
  not found.  It does neither exist as an absolute directory nor in
  '/opt/ros/hydro//usr/include/ni'.  Ask the maintainer 'William Woodall
  <william@osrfoundation.org>, Julius Kammerl <julius@kammerl.de>' to fix it.
Call Stack (most recent call first):
  /opt/ros/hydro/share/gazebo_plugins/cmake/gazebo_pluginsConfig.cmake:154 (find_package)
  /opt/ros/hydro/share/catkin/cmake/catkinConfig.cmake:72 (find_package)
  CMakeLists.txt:7 (find_package)


-- Configuring incomplete, errors occurred!
```

I do not have the include folder `/usr/include/ni` on my system, although all dependencies are fulfilled. If I install the package `libopenni-dev` which contains this folder manually, apt-get wants to remove `ros-hydro-pcl-ros` and all kind of `libpcl-*` packages. There seems to be a conflict / dependency error related to `ros-hydro-pcl-ros`, `openni-dev` and `libopenni-dev`.

Johannes

**Comment by meyerj** [comment]
Just saw the probably related discussion a few days ago on ros/rosdistro#1895.

**Comment by wjwwood** [comment]
Can you make sure you have up-to-date packages, there was a related issue which was resolved recently:

http://lists.ros.org/pipermail/ros-release/2013-September/004203.html

**Comment by meyerj** [comment]
Thanks! This issue seems to be solved with the latest set of `libpcl-*` packages.
