### ISSUE TITLE
NI Not Found

### ISSUE THREAD

**Issue by davetcoleman** [ros-perception/perception_pcl#35]
Myself and several others have run into this problem when installing gazebo_ros_pkgs from source for ROS Hydro. I haven't figured out what is causing it but I have found a workaround where if you uninstall everything (using something like synaptic) related to pcl (libpcl, ros-hydro-pcl, etc) and then re-install them, it seems to work. There's probably some dependency issue that needs to be fixed.

The output:

```
Make Error at /opt/ros/hydro/share/pcl_ros/cmake/pcl_rosConfig.cmake:98 (message):
  Project 'pcl_ros' specifies '/usr/include/ni' as an include dir, which is
  not found.  It does neither exist as an absolute directory nor in
  '/opt/ros/hydro//usr/include/ni'.  Ask the maintainer 'William Woodall
  <william@osrfoundation.org>, Julius Kammerl <julius@kammerl.de>' to fix it.
Call Stack (most recent call first):
  /opt/ros/hydro/share/gazebo_plugins/cmake/gazebo_pluginsConfig.cmake:154 (find_package)
  /opt/ros/hydro/share/gazebo_ros/cmake/gazebo_rosConfig.cmake:154 (find_package)
  /opt/ros/hydro/share/catkin/cmake/catkinConfig.cmake:72 (find_package)
  baxter/baxter_gazebo/CMakeLists.txt:4 (find_package)
```

Thanks!

**Comment by wjwwood** [comment]
If uninstall pcl stuff and reinstalling fixes it then it sounds like a temporary problem related to the state of your system. I don't think there is anything to fix here.

**Comment by wjwwood** [comment]
@davetcoleman If you have an idea how this might be fixed by `pcl_ros` (or any other package) I am interested, I just don't see how I can fix this with a change in dependencies. Further more, having just looked over the dependencies I don't see anything I would consider incorrect, which needs fixing.

**Comment by davetcoleman** [comment]
I don't have an idea I'm afraid. But I've ran into it twice on my machine - I think it occurs when you have both Groovy and Hydro installed. At the least, I thought posting this here might help others who are running into this issue in the short run.

**Comment by georgebrindeiro** [comment]
I just ran into this issue and I have no idea how to fix it, but I have the same kind of setup davetcoleman mentions (both Groovy and Hydro installed). Thanks for the quickfix, Dave.

**Comment by georgebrindeiro** [comment]
I couldn't get it to work by simply reinstalling. I had to manually remove <code>/usr/include/ni</code> from <code>/opt/ros/hydro/share/pcl_ros/cmake/pcl_rosConfig.cmake</code> (although I know I shouldn't edit that directly).

The reason why I don't have /usr/include/ni in the first place is related to this issue: https://github.com/ros-drivers/openni_camera/issues/19

**Comment by wjwwood** [comment]
@tfoote

**Comment by isanchez12** [comment]
Wow, thanks George and Dave.I was dealing with the problem for a few days now, but it has now been fixed with  George's temporary solution. 

Has there been any permanent fix for this problem?

**Comment by LucidOne** [comment]
Does `sudo apt-get update && sudo apt-get upgrade` fix this?
The include is being added automatically by pkg-config, so I think this is an issue with libpcl requiring openni-dev

```
$ grep openni /usr/lib/pkgconfig/pcl_*
/usr/lib/pkgconfig/pcl_io-1.7.pc:Requires:  eigen3 openni-dev pcl_common-1.7 pcl_octree-1.7
/usr/lib/pkgconfig/pcl_visualization-1.7.pc:Requires:  openni-dev pcl_common-1.7 pcl_io-1.7 pcl_kdtree-1.7 pcl_geometry-1.7 pcl_search-1.7
```

**Comment by davetcoleman** [comment]
Is this still an issue? I haven't run into it in a long time (but haven't been using those components). Otherwise I'd suggest we close this issue.

**Comment by LiliMeng** [comment]
I also solved the problem by @georgebrindeiro  's suggestion by  manually removing /usr/include/ni from /opt/ros/hydro/share/pcl_ros/cmake/pcl_rosConfig.cmake

**Comment by kphawkins** [comment]
@davetcoleman 
Came across this bug today but removing `/usr/include/ni` solved my problem.  I had done a fresh install of ROS/PCL just a few weeks ago, so apparently we don't have a permanent fix yet?  I feel like this should be reopened until a patch is integrated.

**Comment by paulbovbel** [comment]
@kphawkins, I'd be happy to dig in to the dependencies some time in the near future, but I'd need some more info.

What ubuntu/ros distros are you using? Was it a fresh install for both? Are you using the PCL PPA?

**Comment by kphawkins** [comment]
Precise/Hydro currently.  At one point I've had Fuerte/Groovy/Hydro all at once.  A few weeks back I was having issues, so I tried to uninstall just about everything ROS + OpenNI to fix a compilation issue whose details escape me at the moment.  I was using the PCL PPA:

```
deb http://ppa.launchpad.net/v-launchpad-jochen-sprickerhof-de/pcl/ubuntu precise main
```

**Comment by paulbovbel** [comment]
I guess it's some sort of inconsistent state issue then. As @wjwwood mentioned, there doesn't seem to be a clear error in the dependencies that would fix this, though I'll see if I can replicate the issue later. Thanks.

**Comment by JacoPisa** [comment]
i'm having the same problem, cannot catkin_make my catkinws, cause of that 
Project 'pcl_ros' specifies '/usr/include/ni' as an include dir, which is
  not found.
but i cannot remove manualy the include, cause i don't have the permission, i saved with chmod the possibility to modify it, but when i save, it say me that:
Could not create a backup file while saving /opt/ros/hydro/share/pcl…cmake/pcl_rosConfig.cmake

how did you modify it??
