### ISSUE TITLE
Unable to build pcl_ros

### ISSUE THREAD

**Issue by MedisettiRameshNaidu** [ros-perception/perception_pcl#360]
I have the source installation of ROS2-foxy and PCL version is 1.12.1
The error is as follows.
*****@*****-GP75-Leopard-10SFK:~/colon_ws2$ colcon build
[0.136s] WARNING:colcon.colcon_core.verb:Some selected packages are already built in one or more underlay workspaces:
	'pcl_conversions' is in: /opt/ros/foxy
	'realsense2_camera_msgs' is in: /opt/ros/foxy
	'realsense2_camera' is in: /opt/ros/foxy
If a package in a merged underlay workspace is overridden and it installs headers, then all packages in the overlay must sort their include directories by workspace order. Failure to do so may result in build failures or undefined behavior at run time.
If the overridden package is used by another package in any underlay, then the overriding package in the overlay must be API and ABI compatible or undefined behavior at run time may occur.

If you understand the risks and want to override a package anyways, add the following to the command line:
	--allow-overriding pcl_conversions realsense2_camera realsense2_camera_msgs

This may be promoted to an error in a future release of colcon-core.
Starting >>> joint_state_publisher
Starting >>> pcl_conversions
Starting >>> realsense2_camera_msgs
Finished <<< pcl_conversions [0.25s]                                                         
Starting >>> pcl_ros
Finished <<< realsense2_camera_msgs [0.38s]                         
Starting >>> realsense2_camera
Starting >>> realsense2_description
Finished <<< realsense2_description [0.07s]                                                    
Finished <<< realsense2_camera [0.12s]                                                         
Finished <<< joint_state_publisher [0.71s]                                                 
Starting >>> joint_state_publisher_gui
Finished <<< joint_state_publisher_gui [0.67s]                                                 
Starting >>> urdf_tutorial
Finished <<< urdf_tutorial [0.06s]                                                       
--- stderr: pcl_ros                             
In file included from /home/*****/colon_ws2/src/perception_pcl/pcl_ros/src/transforms.cpp:38:
/home/*****/colon_ws2/src/perception_pcl/pcl_ros/include/pcl_ros/impl/transforms.hpp:48:10: fatal error: tf2_geometry_msgs/tf2_geometry_msgs.hpp: No such file or directory
   48 | #include <tf2_geometry_msgs/tf2_geometry_msgs.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/pcl_ros_tf.dir/build.make:76: CMakeFiles/pcl_ros_tf.dir/src/transforms.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:141: CMakeFiles/pcl_ros_tf.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
In file included from /home/*****/colon_ws2/src/perception_pcl/pcl_ros/tools/pcd_to_pointcloud.cpp:52:
/usr/local/include/pcl-1.12/pcl/io/io.h:41:22: error: expected constructor, destructor, or type conversion before ‘(’ token
   41 | PCL_DEPRECATED_HEADER(1, 15, "Please include pcl/common/io.h directly.")
      |                      ^
In file included from /usr/local/include/pcl-1.12/pcl/io/io.h:42,
                 from /home/*****/colon_ws2/src/perception_pcl/pcl_ros/tools/pcd_to_pointcloud.cpp:52:
/usr/local/include/pcl-1.12/pcl/common/io.h: In function ‘std::string pcl::getFieldsList(const pcl::PCLPointCloud2&)’:
/usr/local/include/pcl-1.12/pcl/common/io.h:110:17: error: ‘accumulate’ is not a member of ‘std’
  110 |     return std::accumulate(std::next (cloud.fields.begin ()), cloud.fields.end (), cloud.fields[0].name,
      |                 ^~~~~~~~~~
In file included from /usr/local/include/pcl-1.12/pcl/common/io.h:538,
                 from /usr/local/include/pcl-1.12/pcl/io/io.h:42,
                 from /home/*****/colon_ws2/src/perception_pcl/pcl_ros/tools/pcd_to_pointcloud.cpp:52:
/usr/local/include/pcl-1.12/pcl/common/impl/io.hpp: In function ‘void pcl::copyPointCloud(const pcl::PointCloud<PointT>&, const std::vector<pcl::PointIndices>&, pcl::PointCloud<PointOutT>&)’:
/usr/local/include/pcl-1.12/pcl/common/impl/io.hpp:270:26: error: ‘accumulate’ is not a member of ‘std’
  270 |   const auto nr_p = std::accumulate(indices.begin (), indices.end (), 0,
      |                          ^~~~~~~~~~
/home/*****/colon_ws2/src/perception_pcl/pcl_ros/tools/pcd_to_pointcloud.cpp: In constructor ‘pcl_ros::PCDPublisher::PCDPublisher(const rclcpp::NodeOptions&)’:
/home/*****/colon_ws2/src/perception_pcl/pcl_ros/tools/pcd_to_pointcloud.cpp:88:66: error: no matching function for call to ‘pcl_ros::PCDPublisher::declare_parameter<std::string>(const char [10])’
   88 |     file_name_ = this->declare_parameter<std::string>("file_name");
      |                                                                  ^
In file included from /opt/ros/foxy/include/rclcpp/node.hpp:1224,
                 from /opt/ros/foxy/include/rclcpp/executors/single_threaded_executor.hpp:28,
                 from /opt/ros/foxy/include/rclcpp/executors.hpp:22,
                 from /opt/ros/foxy/include/rclcpp/rclcpp.hpp:146,
                 from /home/*****/colon_ws2/src/perception_pcl/pcl_ros/tools/pcd_to_pointcloud.cpp:57:
/opt/ros/foxy/include/rclcpp/node_impl.hpp:157:1: note: candidate: ‘auto rclcpp::Node::declare_parameter(const string&, const ParameterT&, const ParameterDescriptor&, bool) [with ParameterT = std::__cxx11::basic_string<char>; std::string = std::__cxx11::basic_string<char>; rcl_interfaces::msg::ParameterDescriptor = rcl_interfaces::msg::ParameterDescriptor_<std::allocator<void> >]’
  157 | Node::declare_parameter(
      | ^~~~
/opt/ros/foxy/include/rclcpp/node_impl.hpp:157:1: note:   candidate expects 4 arguments, 1 provided
/home/*****/colon_ws2/src/perception_pcl/pcl_ros/tools/pcd_to_pointcloud.cpp:99:42: error: ‘using element_type = class rclcpp::node_interfaces::NodeTopicsInterface’ {aka ‘class rclcpp::node_interfaces::NodeTopicsInterface’} has no member named ‘resolve_topic_name’
   99 |       this->get_node_topics_interface()->resolve_topic_name(cloud_topic_);
      |                                          ^~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/pcd_to_pointcloud_lib.dir/build.make:76: CMakeFiles/pcd_to_pointcloud_lib.dir/tools/pcd_to_pointcloud.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:167: CMakeFiles/pcd_to_pointcloud_lib.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
---
Failed   <<< pcl_ros [3.68s, exited with code 2]

Summary: 7 packages finished [4.02s]
  1 package failed: pcl_ros
  1 package had stderr output: pcl_ros
  1 package not processed

**Comment by ivanpauno** [comment]
You should checkout the [foxy-devel](https://github.com/ros-perception/perception_pcl/tree/foxy-devel) branch when building from source and using Foxy.
