### ISSUE TITLE
Python3 installation, use, examples?

### ISSUE THREAD

**Issue by Petros626** [ros-perception/perception_pcl#363]
Hello,

ROS: Noetic
Python: Python3

I would like to take functions to merge sensor_msgs/PointCloud2 data as described here: https://answers.ros.org/question/58626/merging-multiple-pointcloud2/

I have installed all python packages, like `pcl-ros`, `pcl-msgs`,`pcl-conversions` however I can't call/import and use the latter in my IDE can anyone help me with this?

**Comment by SteveMacenski** [comment]
This is a C++ package.
