### ISSUE TITLE
missing library components in pcl_nodelets.xml

### ISSUE THREAD

**Issue by mickeyxu** [ros-perception/perception_pcl#37]
Hi, I was just wondering, why there are only two library components written in the pcl_nodelets.xml (branch hydro-devel)? why are the other libraries not added, such as "pcl_ros_segmentation"?

Thanks!

**Comment by wjwwood** [comment]
No idea, @jkammerl any clue?

**Comment by LucidOne** [comment]
feel free to send a pull request

**Comment by LucidOne** [comment]
See also #32

**Comment by markpitchless** [comment]
I believe that the idea is to move point cloud pipeline type processing over to ecto. I'm sure I saw a comment/commit somewhere suggesting as much for these extra nodelets and they had been deactivated as being not widely used. But I can't find it anywhere now. Nodelets being bad for pipelines and ecto mentioned here: http://wiki.ros.org/fuerte/Planning/Perception%20Pipelines

**Comment by markpitchless** [comment]
Aha [found it here](http://wiki.ros.org/pcl_ros/Tutorials/SACSegmentationFromNormals%20planar%20segmentation):

```
Deprecated: This tutorial isn't working anymore because two of the needed nodelets have been disabled for building:

r144 | rusu | 2011-11-01 00:44:53 +0100 (Di, 01 Nov 2011) | 2 lines

Disabled nodelets that no longer work with PCL trunk that nobody is using. Switched pipelining of PCL nodelets to ECTO.
```

**Comment by iluetkeb** [comment]
Looks like this issue has been resolved in the meantime (see 271fccfbaa704b899abc4a455ce27a1ab63b6e8d), so we might close this ticket.

btw, while I'm at this, in response to markpitchless's comment, some people still like nodelets, so there's a valid use case here.

**Comment by paulbovbel** [comment]
Agreed

**Comment by jkammerl** [comment]
Yes, I think the idea was to move to ecto. But I am not sure if this ever happened.

**Comment by iluetkeb** [comment]
btw, we might want to pull martimorta's patch into indigo-devel, too.
