### ISSUE TITLE
Project 'pcl_conversions' specifies '/usr/include/vtk-7.1' as an include

### ISSUE THREAD

**Issue by joerowelll** [ros-perception/perception_pcl#390]
I am getting this error when executing catkin build.
My system is Ubuntu 20.04, cmake 3.25.

CMake Error at /opt/ros/noetic/share/pcl_conversions/cmake/pcl_conversionsConfig.cmake:113 (message):
  Project 'pcl_conversions' specifies '/usr/include/vtk-7.1' as an include
  dir, which is not found.  It does neither exist as an absolute directory
  nor in '${{prefix}}//usr/include/vtk-7.1'.  Check the issue tracker
  'https://github.com/ros-perception/perception_pcl/issues' and consider
  creating a ticket if the problem has not been reported yet.

**Comment by mvieth** [comment]
Have you tried installing `libvtk7-dev` via apt?

**Comment by joerowelll** [comment]
That worked, thank you. I was installing just libvtk7 before.
