### ISSUE TITLE
Ros1 dependency in point_cloud.hpp

### ISSUE THREAD

**Issue by aravindSwamy94** [ros-perception/perception_pcl#408]
https://github.com/ros-perception/perception_pcl/blob/6642b7398a4488040c44d48a48308411bcde2228/pcl_ros/include/pcl_ros/point_cloud.hpp#L45

Is this line required. This requires ros1 dependency while building and it throws 
ros/ros.h not found error

Can you please clarify

**Comment by Jack1412** [comment]
Me too, can anyone help, thanks!
