### ISSUE TITLE
Empty data using moving_least_square of pcl_ros 

### ISSUE THREAD

**Issue by mistimohan** [ros-perception/perception_pcl#413]
I am new to Ros and I did not know where to ask for my problem so I am mentioning it here  :
from the pcl_ros page, I found simple tutorials [http://wiki.ros.org/pcl_ros/Tutorials](http://wiki.ros.org/pcl_ros/Tutorials) on how to use nodelets and get filtered point cloud data, which I am visualizing in Rviz.Now when i am using the voxel_grid example,everything is working well as mentioned in the tutorial page [http://wiki.ros.org/pcl_ros/Tutorials/VoxelGrid%20filtering](http://wiki.ros.org/pcl_ros/Tutorials/VoxelGrid%20filtering) .I am also able to change it to normal_estimation which is also working perfectly fine but as soon as i change the nodelet name to moving_least_square and add necessary parameters,the code runs successfully without any output data :

**code:**
<launch>
  <node pkg="nodelet" type="nodelet" name="pcl_manager" args="manager" output="screen" />

  
  <node pkg="nodelet" type="nodelet" name="moving_least_squares" args="load pcl/MovingLeastSquares pcl_manager" output="screen">
    <remap from="~input" to="/iiwa/points2" />
     <rosparam>
      use_polynomial_fit: True 
      polynomial_order: 2 
      search_radius: 0.01
      spatial_locator: 1
    </rosparam> 
  </node>
</launch>

Terminal Launch Output :

started roslaunch server 

SUMMARY
========

PARAMETERS
 * /moving_least_squares/polynomial_order: 2
 * /moving_least_squares/search_radius: 0.01
 * /moving_least_squares/spatial_locator: 1
 * /moving_least_squares/use_polynomial_fit: True
 * /rosdistro: noetic
 * /rosversion: 1.16.0

NODES
  /
    moving_least_squares (nodelet/nodelet)
    pcl_manager (nodelet/nodelet)

ROS_MASTER_URI=http://localhost:11311

process[pcl_manager-1]: started with pid [506159]
process[moving_least_squares-2]: started with pid [506160]
[ INFO] [1683543729.235523468]: Loading nodelet /moving_least_squares of type pcl/MovingLeastSquares to manager pcl_manager with the following remappings:
[ INFO] [1683543729.236303681]: /moving_least_squares/input -> /iiwa/points2
[ INFO] [1683543729.237529465]: waitForService: Service [/pcl_manager/load_nodelet] has not been advertised, waiting...
[ INFO] [1683543729.245983706]: Initializing nodelet with 16 worker threads.
[ INFO] [1683543729.258164755]: waitForService: Service [/pcl_manager/load_nodelet] is now available.
[ WARN] [1683543729.335462770]: [config_callback] use_polynomial_fit is deprecated, use polynomial_order instead!
**Doubt to be Resolved :**
**But when i echo in terminal "rostopic echo /moving_least_squares/normals 
" I get empty data why ?**:
is_dense: True
---
header: 
  seq: 82439
  stamp: 
    secs: 1683543839
    nsecs: 829107000
  frame_id: "world"
height: 1
width: 0
fields: 
  - 
    name: "x"
    offset: 0
    datatype: 7
    count: 1
  - 
    name: "y"
    offset: 4
    datatype: 7
    count: 1
  - 
    name: "z"
    offset: 8
    datatype: 7
    count: 1
  - 
    name: "normal_x"
    offset: 16
    datatype: 7
    count: 1
  - 
    name: "normal_y"
    offset: 20
    datatype: 7
    count: 1
  - 
    name: "normal_z"
    offset: 24
    datatype: 7
    count: 1
  - 
    name: "curvature"
    offset: 32
    datatype: 7
    count: 1
is_bigendian: False
point_step: 48
row_step: 0
data: []
is_dense: True
I do not understand what is going wrong here.I have tried even :
 **rosrun dynamic_reconfigure dynparam get /moving_least_squares**
{'use_polynomial_fit': True, 'spatial_locator': 1, 'polynomial_order': 2, 'search_radius': 0.01, 'gaussian_parameter': 0.02, 'groups': {'id': 0, 'parent': 0, 'name': 'Default', 'type': '', 'state': True, 'groups': {}, 'parameters': {}, 'spatial_locator': 1, 'search_radius': 0.01, 'use_polynomial_fit': True, 'polynomial_order': 2, 'gaussian_parameter': 0.02}}
which also seems to be working fine .Everything is working properly but i am getting no data.There is no problem with point cloud as i have checked it successfully with normal estimation and voxel grid nodelets.

Thank You for your help in advance.

**Comment by SteveMacenski** [comment]
Please do not cross post. ROS Answers question https://answers.ros.org/question/415123/empty-data-using-moving_least_square-of-pcl_ros/

**Comment by mistimohan** [comment]
I thought the ros forum and percention_pcl team are independent of each other.
Sorry for the inconvenience.
Thank you for your information.
