### ISSUE TITLE
Support for ROS2-Foxy

### ISSUE THREAD

**Issue by tejalbarnwal** [ros-perception/perception_pcl#414]
Hey, I see a lot of new features have been added in `ros2` branch, but the updates have not been made into the `foxy-devel` branch.
The [documentation](https://index.ros.org/p/pcl_ros/) suggests using foxy-devel branch as mentioned in vcs-version. 

I am requesting if the features in `ros2` branch could also be supported for ros2-foxy.

**Comment by SteveMacenski** [comment]
Foxy is EOL and will no longer receive support https://docs.ros.org/en/foxy/Releases.html
