### ISSUE TITLE
anyone who compiled this to raspberry pi boards?

### ISSUE THREAD

**Issue by foxydevelby** [ros-perception/perception_pcl#415]
just a question if this package supports arm boards.
tried using --parallel-workers or --executor sequential but the board keeps freezing when reached 83%

**Comment by mvieth** [comment]
@foxydevelby Maybe use top, htop, or similar to monitor the memory usage, and to make sure that only one compile process is used

**Comment by SteveMacenski** [comment]
This seems better suited for the robotics stack exchange (the replacement for ROS Answers)
