### ISSUE TITLE
`pcl::concatenatePointCloud` output row_step is incorrect

### ISSUE THREAD

**Issue by VRichardJP** [ros-perception/perception_pcl#432]
I observed on humble release that the output row_step of `concatenatePointCloud` is the row_step on the first input cloud.

It seems the behavior has been modified by:
https://github.com/ros-perception/perception_pcl/commit/33dbb3bf1fda7b7e5a3382cf36f8961b15d2d8b9

Now the output row_step is the output width, however I think row_step is normally equal to width*point_size.

**Comment by mvieth** [comment]
Yes, you are right. `row_step` is the length of a row in bytes, so `cloud_out.row_step = cloud_out.width`  is not correct. `cloud_out.row_step = cloud_out.width * cloud_out.point_step` should do the right thing.

**Comment by SteveMacenski** [comment]
Can you open a PR?

**Comment by mvieth** [comment]
https://github.com/ros-perception/perception_pcl/pull/433
