### ISSUE TITLE
Release ros2 version for ROS2 iron

### ISSUE THREAD

**Issue by Rayman** [ros-perception/perception_pcl#439]
On Ubuntu 2022.04 when you install `ros-iron-pcl-ros` you still get the ROS1 version (2.4.0). Can you release the ros2 branch on iron?

**Comment by Timple** [comment]
It's only the `include <ros/ros.h>` which is ros1. So a new bloom release which includes this fix: https://github.com/ros-perception/perception_pcl/pull/410 should do it.

**Comment by Timple** [comment]
Actually, the ros2 branch seems to be a half-port.

For example this line: https://github.com/ros-perception/perception_pcl/blob/ros2/pcl_ros/include/pcl_ros/point_cloud.hpp#L155
```
sensor_msgs::PointCloud2
```
Should be 
```
sensor_msgs::msg::PointCloud2
```
So I don't think this file has worked for anyone on ros2 yet.

**Comment by SteveMacenski** [comment]
This repo is not fully ported to ROS 2, this is true. Type masqerading was never fully implemented (mostly because masqerading didn't exist for a long time). You can see a number of things are commented out and not being compiled [1]

[1] https://github.com/ros-perception/perception_pcl/blob/ros2/pcl_ros/CMakeLists.txt

**Comment by mvieth** [comment]
There is a pull request which fixes the types on the `ros2` branch: https://github.com/ros-perception/perception_pcl/pull/425

**Comment by shu-beg** [comment]
Is there any update regarding the release of already ported features? I had a short look into [perception_pcl-release](https://github.com/ros2-gbp/perception_pcl-release) and it seems as there was an attempt to release at least 2.4.1 but for humble / iron / rolling there is still only 2.4.0 available as debian? Anyways, as there are quite useful features available on ros2 branch compared to 2.4.1 (e.g. filters) I would really appreciate a new release.

**Comment by SteveMacenski** [comment]
Figuring it out now, I'm rolling back locally the ros2 branch to the last sync and branching off humble / iron and going to roll forward those commits that are API/ABI compatiable and then run a sync over those with the subset of `ros2` changes that are appropriate. I'll also update Rolling. 

Currently in progress.

**Comment by SteveMacenski** [comment]
My apologies, I'm not sure how this fell so far off my radar for so long

**Comment by Rayman** [comment]
@shu-beg https://github.com/ros/rosdistro/pull/40476

**Comment by Rayman** [comment]
Last sync we caused a regression on the 2.5.1 release for iron. Can we try again next sync? The filter nodes are very useful to have.

**Comment by SteveMacenski** [comment]
Was that fixed in iron branch? I can run again if we're good to go again.

Sorry, I've had alot on my plate and some things have been intentionally dropped. I'm getting onto the right side of that pile of work this week hopefully :-) Open source maintainers' work is never done, but at some point I as a human need to be done :laughing:

**Comment by Rayman** [comment]
I think we need this PR: https://github.com/ros-perception/perception_pcl/pull/447

So if you cherry pick that commit to iron you should be good to go.

For me personally I would like to see the whole rolling branch released on iron. A lot more code has been ported from ROS1 to ROS2. But I can imagine that would break ABI compatibility

**Comment by SteveMacenski** [comment]
https://github.com/ros/rosdistro/pull/41386
