### ISSUE TITLE
bag_to_pcd does not support tf2

### ISSUE THREAD

**Issue by LucidOne** [ros-perception/perception_pcl#46]
Support for tf2 needed for Hydro and later

This is the quick way of fixing it.

Patch

```
diff --git a/pcl_ros/tools/bag_to_pcd.cpp b/pcl_ros/tools/bag_to_pcd.cpp
index b9114cf..d1ec14e 100644
--- a/pcl_ros/tools/bag_to_pcd.cpp
+++ b/pcl_ros/tools/bag_to_pcd.cpp
@@ -91,6 +91,7 @@ int

   view.addQuery (bag, rosbag::TypeQuery ("sensor_msgs/PointCloud2"));
   view.addQuery (bag, rosbag::TypeQuery ("tf/tfMessage"));
+  view.addQuery (bag, rosbag::TypeQuery ("tf2_msgs/TFMessage"));
   view_it = view.begin ();

   std::string output_dir = std::string (argv[3]);

```

If there is an example of the preferred migration approach I'd be happy to produce a patch.

**Comment by wjwwood** [comment]
Can you make that a pull request?

Github will make one for you, just edit the file here: https://github.com/ros-perception/perception_pcl/edit/hydro-devel/pcl_ros/tools/bag_to_pcd.cpp

**Comment by LucidOne** [comment]
Content preview:  On 04/07/2014 04:10 PM, William Woodall wrote: > > Can you
    make that a pull request? > > Github will make one for you, just edit the
    file here: > https://github.com/ros-perception/perception_pcl/edit/hydro-devel/pcl_ros/tools/bag_to_pcd.cpp
    > > — > Reply to this email directly or view it on GitHub > https://github.com/ros-perception/perception_pcl/issues/46#issuecomment-39777305.
    > No problem. [...] 

 Content analysis details:   (-2.9 points, 5.0 required)

  pts rule name              description

---

 -1.0 ALL_TRUSTED            Passed through trusted hosts only via SMTP
 -1.9 BAYES_00               BODY: Bayes spam probability is 0 to 1%
                             [score: 0.0000]
