### ISSUE TITLE
New merge in ros2 branch is no longer working for Humble

### ISSUE THREAD

**Issue by wy-chien** [ros-perception/perception_pcl#473]
I know this is not a bug. This is just a reminder for those using `ros2` branch along with Humble.

Two weeks ago, the [Merge](https://github.com/ros-perception/perception_pcl/pull/472) updated some headers from `.h` to `.hpp`, which is no longer working with the Humble version.

The reason I was using the combination is the `cropbox` function. For those who have the same demand, you can check out the commit `f127921808b1c6fb6237a7e4cf19d16b85a0e43b`

```bash
cd perception_pcl
git checkout f127921808b1c6fb6237a7e4cf19d16b85a0e43b
```

**Comment by Rayman** [comment]
There is a humble branch with the code that is deployed for humble to the buildfarm
