### ISSUE TITLE
Indigo Release

### ISSUE THREAD

**Issue by DLu** [ros-perception/perception_pcl#48]
This is just a request for there to be an indigo release of pcl_ros, so that people can track the maintainer's progress.

**Comment by paulbovbel** [comment]
Maintainter-ship was just handed over, so a release is imminent, thanks for your patience.

**Comment by DLu** [comment]
Great! I knew things were in flux and just set this up to track the progress. Thanks for the support.

**Comment by LucidOne** [comment]
It built with minimal issues and I am running some tests now.

**Comment by LucidOne** [comment]
I would like to see #47 applied indigo-devel before initial release

**Comment by paulbovbel** [comment]
Put in https://github.com/ros-perception/perception_pcl/pull/47 and release when you're ready, then we can start going through the other issues/pulls at leisure.

**Comment by LucidOne** [comment]
#47 tested and applied to hydro-devel
#47 and indigo-devel tested with velodyne data and pcd viewer
Updating package.xml files now
