### ISSUE TITLE
pcl_ros executables installed to wrong place in groovy

### ISSUE THREAD

**Issue by togaen** [ros-perception/perception_pcl#5]
The executables for the pcl_ros package are installed to /opt/ros/groovy/bin, which means that rosrun cannot find them. See this page: http://answers.ros.org/question/54132/pcl_ros-bag_to_pcd-not-found/

**Comment by tkruse** [comment]
Also see https://groups.google.com/d/topic/ros-sig-buildsystem/hsxeJocnKIQ/discussion

**Comment by jack-oquin** [comment]
I do think this is a bug. But, one could argue that these script names are sufficiently descriptive to legitimately install in the main /opt/ros/DISTRO/bin directory.

Regardless, the effect of fixing this in Groovy needs to be considered carefully. People who are already adapting to the new placement will be broken if it suddenly moves to the package-local directory, `$PREFIX/lib/pcl_ros`. Ideally, it should be installed in both places for Groovy with the DISTRO/bin placement deprecated. Then a proper fix can be released in Hydro. 

That sounds like a lot of work.

**Comment by jkammerl** [comment]
Thanks for bringing this up! Yes, I agree the perception_pcl tools shouldn't be globally installed. I added install targets to $PREFIX/lib/pcl_ros and we will remove them in Hydro from DISTRO/bin.

**Comment by tkruse** [comment]
It helps to point to the commit that fixes the issue:
d0e2a9ddd
