### ISSUE TITLE
pcl_ros errors while installing rgbdslam hydro

### ISSUE THREAD

**Issue by LiliMeng** [ros-perception/perception_pcl#57]
Hey,
    I just followed the procedure from this website: (http://felixendres.github.io/rgbdslam_v2/) to install rgbdslam, it goes well until the step 4: To build RGBDSLAMv2 go to your catkine workspace and execute "catkin_make".

After I execute "catkin_make", the following errors occurred: 

```
      CMake Error at /opt/ros/hydro/share/pcl_ros/cmake/pcl_rosConfig.cmake:106 (message):
  Project 'pcl_ros' specifies '/usr/include/ni' as an include dir, which is
  not found.  It does neither exist as an absolute directory nor in
  '/opt/ros/hydro//usr/include/ni'.  Ask the maintainer 'Paul Bovbel
  <paul@bovbel.com>, Bill Morris <bill@neautomation.com>' to fix it.
Call Stack (most recent call first):
  /opt/ros/hydro/share/catkin/cmake/catkinConfig.cmake:72 (find_package)
  rgbdslam_v2/CMakeLists.txt:42 (find_package)

-- Configuring incomplete, errors occurred!
make: *** [cmake_check_build_system] Error 1
Invoking "make cmake_check_build_system" failed
```

Could anyone provide some suggestions? Thank you so much in advance! 

Best,
Lili

**Comment by LiliMeng** [comment]
It seems that similar problems have occurred before: https://github.com/ros-perception/perception_pcl/issues/35

**Comment by LiliMeng** [comment]
I also solved the problem by @georgebrindeiro 's suggestion by manually removing /usr/include/ni from /opt/ros/hydro/share/pcl_ros/cmake/pcl_rosConfig.cmake

**Comment by unghee** [comment]
For future reference, installing openni version 1.5.4. from source solved the problem.
