### ISSUE TITLE
  Allow pcl/PassThrough nodelet to have filter limits outside the range [-1000, 1000]

### ISSUE THREAD

**Issue by dani-carbonell** [ros-perception/perception_pcl#69]
Restricting allowed values for filter_limit_min, filter_limit_max parameters to range [-1000,1000]
is still too low for the intenstity field for example. I am using a Hokuyo UTM-30lx and it's giving values up to 40000.0 so I am not able to filter the pointcloud properly.

**Comment by paulbovbel** [comment]
I see no problem with raising them again, can you suggest some sane limits for your application, and please feel free to do a pull to expedite. Thanks!

**Comment by dani-carbonell** [comment]
For my application a value of 50000 is enough but for other channels of a pointcloud could be still low. What should we do?

**Comment by dani-carbonell** [comment]
I have done a pull request with the value 100000,00.
ee96100

**Comment by paulbovbel** [comment]
Merged, thanks
