### ISSUE TITLE
does not produce correct scans when using Gazebo kenetic 

### ISSUE THREAD

**Issue by rnunziata** [ros-perception/perception_pcl#83]
does not produce correct scans when using Gazebo kinetic plugin.Missing intensities and leading data does not match normal laser output values for simulated laser plugin.

**Comment by paulbovbel** [comment]
You'll have to be more specific. pointcloud_to_laserscan does not provide intensity data, not sure what you mean by 'leading data'. I'm open to proposals about what intensity data could represent.

**Comment by rnunziata** [comment]
Was unaware that it does not produce intensities. I have no suggestions. The leading data issues have just been a wrong parameter setting on my part. Issue closed.
