### ISSUE TITLE
This may or may not be an issue I am unable to find a solution 

### ISSUE THREAD

**Issue by rnunziata** [ros-perception/perception_pcl#84]
I am running pointcloud_to_laserscan . 
Reinstatement of issue: I am using the gazebo kinetic camera plugin. If I send the /depth/points to pointcloud_to_laserscan it does not seem to produce as usable scan output. So that gmapping complains that it is no mounted as planer ...

**Comment by LucidOne** [comment]
Do you have a launch file? Error logs?
Have you tried running roslaunch with the --screen option?

**Comment by SteveMacenski** [comment]
Inactive, closing
