### ISSUE TITLE
Need bloom releases for Jade, Indigo and maybe Hydro

### ISSUE THREAD

**Issue by LucidOne** [ros-perception/perception_pcl#95]
I think #87 was the last merge for Hydro

**Comment by LucidOne** [comment]
It would be nice if #94 could be merged before the release

**Comment by LucidOne** [comment]
It may also be worth bumping the version numbers for indigo/jade

**Comment by paulbovbel** [comment]
I think maybe a hydro release should be avoided since buildfarms are about to go down, and we don't want to introduce a regression

**Comment by LucidOne** [comment]
Sounds like a plan
